hangfire-postgres/Hangfire.PostgreSql

src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj, src/Hangfire.PostgreSql/Install.v5.sql
Due to new format of server name in Hangfire
(https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Server/BackgroundProcessingServer.cs#L166)
the old size of server.id column is not applicable for storing such strings.
=> Added migration for Hangfire >=1.5

src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj, src/Hangfire.PostgreSql/Install.v3.sql, src/Hangfire.PostgreSql/Install.v4.sql, src/Hangfire.PostgreSql/Install.v5.sql, src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs, src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs, src/Hangfire.PostgreSql/PostgreSqlObjectsInstaller.cs, src/Hangfire.PostgreSql/packages.config, tests/Hangfire.PostgreSql.Tests/Hangfire.PostgreSql.Tests.csproj, tests/Hangfire.PostgreSql.Tests/packages.config
This fixes #16. npgsql version 3 is now official and recommended. Following the [migration guide](http://www.npgsql.org/doc/migration-3.0.html) this PR:
1. Sends IEnumerable parameters as lists (`.ToList()`)
2. Types parameters as arrays `(@p)` instead of `@p`
3. Splits `CREATE` statements from `INSERT`/`UPDATE` when creating the schema, due to npgsql/npgsql#641
Have done a bit of testing -- seems to work well :-).
=> Add support for npgsql version 3

src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs
Hi,
I already created a pull request at https://github.com/HangfireIO/Hangfire/pull/297.
`GetTimelineStats` and `GetHourlyTimelineStats` job counts may be assigned to the wrong dates. The problem is that in the last loop where the result is generated the matching of the value of `valuesMap[valuesMap.Keys.ElementAt(i)]` and the date `dates[i]` are not correct.
for (var i = 0; i < dates.Count; i++)
{
var value = valuesMap[valuesMap.Keys.ElementAt(i)]; // valuesMap.Keys may be unsorted if keys were missing and added via valuesMap.Add(key, 0);
result.Add(dates[i], value); // dates are sorted
}
I also refactored some duplicated code into a separate function.
=> Fix GetTimelineStats / GetHourlyTimelineStats incorrect order

src/Hangfire.PostgreSql/packages.config
I've just upgraded a local project to 3.1.2 of NpgSql and they've changed the exception API quite considerably which breaks your library. Am on mobile at the moment so made the changes in github that I know about - but I'm sure you'll want to just make sure it compiles with the new version directly.
Cheers!
=> Update to make compatible with NpgSql 3.1.2

src/Hangfire.PostgreSql/Entities/JobParameter.cs, src/Hangfire.PostgreSql/Entities/Server.cs, src/Hangfire.PostgreSql/Entities/SqlHash.cs, src/Hangfire.PostgreSql/Entities/SqlJob.cs, src/Hangfire.PostgreSql/Entities/SqlState.cs, src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj, src/Hangfire.PostgreSql/Install.v7.sql, src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs, src/Hangfire.PostgreSql/PostgreSqlStorageOptions.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlDistributedLockFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageOptionsFacts.cs
Sometimes I faced problem when my service is stopped incorrectly and in this case distributed lock becomes "dead". After restarting service it couldn't fetch any jobs. My workaround was to manually clean lock table in db, so I decided to implement distributed lock timeout.
In this commit:
- Added option DistributedLockTimeout to PostgreSqlStorageOption
- Implemented removing dead locks in PostgresDistributedLock
- Added schema migration (added column "acquired" to "lock" table)
- Updated test cases 
- Db entities marked as UsedImplicilty
=> Implemented distributed lock timeout

src/Hangfire.PostgreSql.NetCore/PostgreSqlBootstrapperConfigurationExtensions.cs
This enables easy configuration with:
```
public void ConfigureServices(IServiceCollection services)
{
services.AddHangfire(config =>
{
config.UsePostgreSqlStorage("");
});
}
```
=> Added IGlobalConfiguration overloads to UsePostgreSqlStorage

appveyor.yml
Appveyor test discovery fails to correctly run .net core tests and should be disabled. Tests would be started by build script.
https://ci.appveyor.com/project/SonicGD/hangfire-postgresql/build/1.4.0.28 - now green
=> Appveyor tests discovery should be disabled

.gitignore, global.json, psake-project.ps1
This allows to pack both `net452` and `coreapp`. Explanation of changes:
1) `.gitignore` -  explude project.lock.json located in _tests_ 
2) `global.json` - since preview 4 of SDK released which relies on `cproj` and not `project.json` I had to lock the version of SDK to `1.0.0-preview2-003121`, otherwise `dotnet` will pick the latest version of SDK installed on machine and this won't find cproj file, thus the build will fail. The other option is to migrate to cproj. I don't mind doing it, but personally think it is too soon. LMK what you think.
#54
=> Nuget packaging for .net core

src/Hangfire.PostgreSql/Install.v9.sql
Resource name should not be limited by size.
This is making Hangfire fail when queue names are longer than 100 characters.
We applied this change in our systems to fix the issue.
Also more globally, limits should not be applied to character varying on PostgreSQL. (TEXT is always the way to go): https://dba.stackexchange.com/questions/20974/should-i-add-an-arbitrary-length-limit-to-varchar-columns
=> Set lock resource column to TEXT type

src/Hangfire.PostgreSql/ExpirationManager.cs, src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj, src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs, src/Hangfire.PostgreSql/PostgreSqlDistributedLockException.cs, src/Hangfire.PostgreSql/PostgreSqlFetchedJob.cs, src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs, src/Hangfire.PostgreSql/PostgreSqlJobQueueProvider.cs, src/Hangfire.PostgreSql/PostgreSqlObjectsInstaller.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, tests/Hangfire.PostgreSql.Tests/Hangfire.PostgreSql.Tests.csproj
Npgsql 4 supports netstandard2 only, so support for netstandard 1.* has been removed.
=> Upgrade to netstandard2 and Npgsql 4.0.3 - Issue #89

src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs
We wish to perform some custom connection setup and would prefer not to copy the entire `PostgreSqlMonitoringApi` class.
=> Make PostgreSqlMonitoringApi extensible.

src/Hangfire.PostgreSql/Entities/JobParameter.cs, src/Hangfire.PostgreSql/Entities/SqlHash.cs, src/Hangfire.PostgreSql/Entities/SqlJob.cs, src/Hangfire.PostgreSql/Entities/SqlState.cs, src/Hangfire.PostgreSql/IPersistentJobQueueMonitoringApi.cs, src/Hangfire.PostgreSql/Install.v11.sql, src/Hangfire.PostgreSql/PostgreSqlConnection.cs, src/Hangfire.PostgreSql/PostgreSqlFetchedJob.cs, src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs, src/Hangfire.PostgreSql/PostgreSqlJobQueueMonitoringApi.cs, src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs, tests/Hangfire.PostgreSql.Tests/ExpirationManagerFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlConnectionFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlFetchedJobFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlJobQueueFacts.cs
this migrate's all int's to long so that there is a bigger amount of id's that could be handled with Hangfire.PostgreSql.
Another good extension would be to cycle the sequences.
Currently PostgreSql has support for that, however that assumes, that no old id exists, which is problematic since failed jobs are still inside the JobId table.
=> migrate id's from int to long

src/Hangfire.PostgreSql/Install.v11.sql
From Postgres documentation:
> Sequences are based on bigint arithmetic, so the range cannot exceed the range of an eight-byte integer (-9223372036854775808 to 9223372036854775807).
I also checked that current sequence (before v11 migration) max value is set to 9223372036854775807 as expected via:
```sql
SELECT max_value FROM job_id_seq;
```
Fixes #111.
More info [here](https://github.com/frankhommers/Hangfire.PostgreSql/issues/111#issuecomment-504794536).
=> Don't alter sequences as they're already bigint

src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, tests/Hangfire.PostgreSql.Tests/Hangfire.PostgreSql.Tests.csproj, tests/Hangfire.PostgreSql.Tests/PostgreSqlMonitoringApiFacts.cs, tests/Hangfire.PostgreSql.Tests/Utils/ConnectionUtils.cs
Cause of the connection issues:
The "_existingConnection" property was NULL when calling the "GetMonitoringApi" method, which resulted in a new connection each time calling it.
Fixes #124 and fixes #127
=> Changes to fix the connection issues for both Non-SSL and SSL encrypted databases (#124 and #127)

src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, src/Hangfire.PostgreSql/PostgreSqlStorageOptions.cs, src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs, tests/Hangfire.PostgreSql.Tests/ExpirationManagerFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlConnectionFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlWriteOnlyTransactionFacts.cs, tests/Hangfire.PostgreSql.Tests/Utils/ConnectionUtils.cs
Add transaction scope support by using TransactionScope in `PostgreSqlWriteOnlyTransaction`  and by removing `Enlist = false` in JobStorage which enables auto enlisting when creating a new job (`CreateExpiredJob`).
For backwards compatibility reason (not breaking existing apps), ambient tx enlistment must be manually switched on by setting the new `EnableTransactionScopeEnlistment` property to "true". 
Note: Npgsql auto enlists into TransactionScope since 3.x.
Also added 2 new test cases, which assert that transactions correctly enlist in the ambient transaction if provided. All existing tests are passing.
We would love too have this in as soon as possible. Let me know what you think ;-)
=> Add transaction scope support

src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs
This restores the previous tx timeout before the TransactionScope changes were introduced in 93e1f606.
See https://github.com/frankhommers/Hangfire.PostgreSql/issues/119 for context.
=> Set Transaction Timeout of TransactionScope to maximum value.

src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj, src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs
Fix issue with culture-sensitive `.ToString()` in `PostgreSqlJobQueue.cs`, causing exceptions like `
invalid input syntax for type interval: "−invalid input syntax for type interval: "−1800 SECONDS"1800 SECONDS"
`
The PR does a specific `.ToString(CultureInfo.InvariantInfo)`, which should behave consistently regardless of current `CultureInfo.CurrentCulture`.
A reference to [Microsoft.NETFramework.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/) has also been added, as the Hangfire.PostgreSQL won't build on a machine with only the .NET Core SDK installed. This does not change the dependencies of the resulting nupkg.
=> Fix number formatting of input to PostgreSQL INTERVAL function

src/Hangfire.PostgreSql/IPersistentJobQueue.cs, src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs, src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlJobQueueFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlWriteOnlyTransactionFacts.cs
Fixes #158 
The issue can easily be fixed by passing a db connection to `PostgreSqlJobQueue.Enqueue`. The implementation is the same as in `Hangfire.SqlServer`. See [Hangfire.SqlServer/IPersistentJobQueue.cs](https://github.com/HangfireIO/Hangfire/blob/88af1e4c98fe1c1a24c21a99d350bc7f1ed7d575/src/Hangfire.SqlServer/IPersistentJobQueue.cs#L27) and [Hangfire.SqlServer/SqlServerJobQueue.cs](https://github.com/HangfireIO/Hangfire/blob/88af1e4c98fe1c1a24c21a99d350bc7f1ed7d575/src/Hangfire.SqlServer/SqlServerJobQueue.cs#L72).
=> Enqueueing a job does not trigger a prepared transaction anymore when using transaction scope enlistment

src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs
**ISSUE:**
When a background server has more than 1 worker (10 workers count in my test), they try to fetch same row.
Although this is being handled by smoothException, it causes a lot of missed fetch by the multiple workers. 
When jobs duration is short, concurrent update issue happens more often. 
Same issue also reported here https://github.com/frankhommers/Hangfire.PostgreSql/issues/139
**Solution:**
Adding a hint to skip locked rows allows next worker to pick up next unclaimed item. From my testing, all 10 workers got unique jobs in each pass. 
Changing Isolation level from RepeatableRead to ReadCommitted since we skip the locked rows.
=> addressed concurrent update issue

src/Hangfire.PostgreSql/Scripts/Install.v13.sql
Remove the hardcoded "hangfire" schema to prevent errors when a custom schema is specified in .NET Core.
Fixes issue: https://github.com/frankhommers/Hangfire.PostgreSql/issues/173
=> Removed hangfire schema in Install.v13.sql

src/Hangfire.PostgreSql/PostgreSqlConnection.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlConnectionFacts.cs
This fix addresses https://github.com/frankhommers/Hangfire.PostgreSql/issues/167.
I also did some manual testing to make sure these changes work with Hangfire. I created a small ASPNET.Core app and configured Hangfire+Postgre with a single processing server. Then, I manually deleted all the records from `Server` table.
Here is the log output from Hangfire (since the moment when the server record was deleted):
```log
warn: Hangfire.Server.ServerHeartbeatProcess[0]
Server desktop-4ma8jcd:13924:333a1381 was considered dead by other servers, restarting...
info: Hangfire.Server.BackgroundServerProcess[0]
Server desktop-4ma8jcd:13924:333a1381 caught restart signal...
warn: Hangfire.Server.BackgroundServerProcess[0]
Server desktop-4ma8jcd:13924:333a1381 stopped non-gracefully due to …
```
=> Disappeared server restart fix

src/Hangfire.PostgreSql/Scripts/Install.v10.sql, src/Hangfire.PostgreSql/Scripts/Install.v11.sql, src/Hangfire.PostgreSql/Scripts/Install.v12.sql, src/Hangfire.PostgreSql/Scripts/Install.v13.sql, src/Hangfire.PostgreSql/Scripts/Install.v3.sql, src/Hangfire.PostgreSql/Scripts/Install.v4.sql, src/Hangfire.PostgreSql/Scripts/Install.v5.sql, src/Hangfire.PostgreSql/Scripts/Install.v6.sql, src/Hangfire.PostgreSql/Scripts/Install.v7.sql, src/Hangfire.PostgreSql/Scripts/Install.v8.sql, src/Hangfire.PostgreSql/Scripts/Install.v9.sql
This fix addresses #109.
Resetting search_path in the end of every install script to prevent errors with connection re-using in connection pools.
=> Reset search_path in the end of every install script

src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs
#179 stop the exception propagation if the fetched job was concurrently fetched by another worker
=> Fixes #179: Concurrent fetch handling improvement

src/Hangfire.PostgreSql/Scripts/Install.v14.sql
Hello,
Reverts the installer script change made (accidentally?) during https://github.com/frankhommers/Hangfire.PostgreSql/commit/0c48d67066fe1c38d45bbc632db98aba8df9bd09
As others reported, I am also seeing `22023: MAXVALUE (9223372036854775807) is out of range for sequence data type integer `  during schema update as per https://github.com/frankhommers/Hangfire.PostgreSql/issues/201
Importantly, the column is NOT moved to `bigint` and this schema `v14` is not applied (and fails again on next startup).
Was it intentional that the order of begin/exception statements changed in "version bump" commit at https://github.com/frankhommers/Hangfire.PostgreSql/commit/0c48d67066fe1c38d45bbc632db98aba8df9bd09 ?
Under pg13.x the first `ALTER SEQUENCE hangfire.job_id_seq MAXVALUE 9223372036854775807` …
=> Revert (accidental?) change that prevents Install.v14.sql from succeeding

src/Hangfire.PostgreSql/ExpirationManager.cs, src/Hangfire.PostgreSql/PostgreSqlStorageOptions.cs, src/Hangfire.PostgreSql/Scripts/Install.v15.sql, tests/Hangfire.PostgreSql.Tests/PostgreSqlInstallerFacts.cs
This PR addresses #193 and #194 by exposing two new `PostgresStorageOptions` properties, and adding missing indexes to help with the expiration queries performance in `ExpirationManager`.
`PostgresStorageOptions` now supports:
1. `JobExpirationCheckInterval`: How often expiration of expired job resources are cleaned up (defaults to existing value of 1 hour)
2. `DeleteExpiredBatchSize`: How many records may be deleted per batch run of the expiration manager (defaults to existing value of 1000)
New indexes have also been added to `job, list, set, hash` on the `expireat` column to help with the `ExpirationManager` delete query performance mentioned in #194 . The `counter` table that is also part of the expiration cleanup already has an index on `expireat`.
=> Improve ExpirationManager performance and options

src/Hangfire.PostgreSql/ExpirationManager.cs, src/Hangfire.PostgreSql/PersistentJobQueueProviderCollection.cs, src/Hangfire.PostgreSql/PostgreSqlConnection.cs, src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs, src/Hangfire.PostgreSql/PostgreSqlFetchedJob.cs, src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs, src/Hangfire.PostgreSql/PostgreSqlJobQueueMonitoringApi.cs, src/Hangfire.PostgreSql/PostgreSqlJobQueueProvider.cs, src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, src/Hangfire.PostgreSql/PostgreSqlStorageOptions.cs, src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs, tests/Hangfire.PostgreSql.Tests/ExpirationManagerFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlConnectionFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlDistributedLockFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlFetchedJobFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlJobQueueFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlMonitoringApiFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlWriteOnlyTransactionFacts.cs, tests/Hangfire.PostgreSql.Tests/Utils/PostgreSqlStorageExtensions.cs, tests/Hangfire.PostgreSql.Tests/Utils/PostgreSqlStorageFixture.cs
Many times we've been hit by the pool exhaustion exceptions when running the hangfire instance using this provider. Changes in this PR are somewhat copied over from Hangfire.SqlServer provider. Idea is to use one connection for a single resource.
We've been running this DLL for 4 months now and haven't experienced another exception related to connection pool since then.
=> Fix SQL connection pool exhaustion issues

README.md, appveyor.yml, build.cake, build.ps1, src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj
Fixes #222.
Multiple packages will be published to NuGet after these changes, first one as usual, the second (named Hangfire.PostgreSql.Npgsql5) will contain reference to Npgsql5+ instead of 6+.
=> Bring back support for Npgsql 5

src/Hangfire.PostgreSql/EnvironmentHelpers.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs
Fixes #225 
As noted in the issue, this exception only appeared on Linux.
An existing unit test for the transaction enlistment actually failed when ran within Linux (dotnet-sdk). This test now succeeds. `Hangfire.PostgreSql.Tests.PostgreSqlConnectionFacts.CreateExpiredJob_EnlistsInTransaction`.
Another test currently fails on my machine, but it did that also without any of my changes. So I guess it's not affected by this MR (`SetRangeInHash_DoesNotThrowSerializationException` with timeouts).
Possible breaking changes:  
I guess nothing, as the transaction scope enlistment has to be explicitly activated and then it behaves as expected.
How to test:  
If you happen not to have Linux at hand, but have Docker running, you can simply test it with the following line:
```
docker run -v …
```
=> Fixed exception when enqueuing a job within an existing transaction scope

appveyor.yml
This allows both builds to be tested separately, instead of one build's test results overwriting the previous builds results, see https://ci.appveyor.com/project/AndrewA/hangfire-postgresql/builds/42029011 for an example. Note that nupkg artifacts are now separated.
This helps reveal the test failures in CI that occur under Npgsql v6 with a non-UTC time zone set, see #232
Note that the version 5 and 6 values used for `BUILD_NPGSQL_VERSION` env var is only parsed to be `5` or anything else (to mean `6`) as per https://github.com/frankhommers/Hangfire.PostgreSql/pull/224/files#diff-7058d51fab2cfa0f0ff04d78a112d95507be445c0f9c1a38bb0a780513482f4bR50-R67
See https://www.appveyor.com/docs/build-configuration/#build-matrix
=> Use 'matrix builds' with AppVeyor CI to run Npgsql 5 and 6 builds separately

appveyor.yml, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageFacts.cs, tests/Hangfire.PostgreSql.Tests/Utils/ConnectionUtils.cs
Ensure we always use UTC as the connection's timezone setting for Npgsql 6 compatibility when the default differs from UTC
Npgsql 6 introduced changes in to how DateTimes are handled with "timestamp without time zone" column, basically converting timestamps to the connection time zone as per https://www.npgsql.org/efcore/release-notes/6.0.html?tabs=annotations
This change ensures we restore previous behaviour by (re)setting the connection's session timezone to UTC, in case the default differs on the database server
This PR builds upon #232 to demonstrate test success, see https://ci.appveyor.com/project/AndrewA/hangfire-postgresql/builds/42029218
=> Always use UTC timezone for connection to ensure Npgsql 6 compatibility

src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs
After implementing #188, people were scared that the library started having issues with acquiring locks. All of that was due to logging warnings, which was hidden completely before.
This PR changes the log level to Trace (which is very rarely used, mostly to investigate stuff) for serialization failures specifically (as that exception is handled properly). Any other exception will still be logged as warning.
=> Changed serialization failure when acquiring lock to debug log level

src/Hangfire.PostgreSql/Scripts/Install.v17.sql, tests/Hangfire.PostgreSql.Tests/PostgreSqlInstallerFacts.cs
We noticed that the following query was between the top executed queries and also that the total time taken by this query was more than the total time taken by all the other queries for the hangfire db.
```
SELECT value 
FROM hangfire.set
WHERE key = ? AND score BETWEEN ? AND ? 
ORDER BY score 
LIMIT ?
```
We created the following index:
```
CREATE INDEX IF NOT EXISTS ix_hangfire_set_key_score ON hangfire."set" (key, score);
```
And that helped:
We thought it might make sense to add the creation of this index to the install scripts.
=> Create index on the "set" table

src/Hangfire.PostgreSql/IConnectionFactory.cs, src/Hangfire.PostgreSql/PostgreSqlBootstrapperConfigurationExtensions.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageFacts.cs, tests/Hangfire.PostgreSql.Tests/Utils/DefaultConnectionFactory.cs
Hi. In the company where I work a lot of teams use your resources. Unfortunately `PostgreSqlStorage` only uses an existing connection or `connectionString f or the duration of the store.
In our postgres infrastructure databases can change their roles (for example, move from the **master** role to **read-only**) or addresses at any time the service is running.
In normal work we always create an `NpgsqlConnection` with the correct values ​​that we get through our own implementation of service discovery.
We really miss the support for dynamic connection creation in `PostgreSqlStorage`. I have implemented a simple support for such cases in the form of the `IConnectionFactory` interface which third-party developers can implement on their own side.
It would be great if such support was in your …
=> Add connection factory for support dynamic create NpgsqlConnection in PostgreSqlStorage

src/Hangfire.PostgreSql/PostgreSqlStorage.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageFacts.cs
Fixed https://github.com/frankhommers/Hangfire.PostgreSql/issues/258
Existing transaction taken into account for picking isolation level instead of always using ReadCommitted by default.
=> Fixed an issue #258 

src/Hangfire.PostgreSql/CountersAggregator.cs, src/Hangfire.PostgreSql/ExpirationManager.cs, src/Hangfire.PostgreSql/PostgreSqlConnection.cs, src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, src/Hangfire.PostgreSql/PostgreSqlStorageOptions.cs, src/Hangfire.PostgreSql/Scripts/Install.v18.sql
Using Hangfire.SqlServer as a reference I implemented the counters aggregator functionality. The actual SQL implementation differs a bit (due to `MERGE` only being available in PostgreSQL 15) but I'm basically doing an upsert in the aggregate table, then deleting the records from the counters table, all within a transaction.
I also updated `PostgreSqlMonitoringApi.cs` to pull in the two values via a `UNION ALL` and sum them together, exactly as seen in the SQL Server implementation. Finally, I updated `ExpirationManager.cs` to expire old records in the new aggregate table. 
I'm unfamiliar with the schema management system here, so I just created a new v18 install script. If someone could test that functionality, that would be great.
=> Implemented Counters Aggregator

src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj, src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs, src/Hangfire.PostgreSql/PostgreSqlDistributedLockException.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, src/Hangfire.PostgreSql/PostgreSqlStorageOptions.cs, src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs, src/Hangfire.PostgreSql/Utils/ConnectionStringBuilderExtensions.cs, src/Hangfire.PostgreSql/Utils/TransactionHelpers.cs, tests/Hangfire.PostgreSql.Tests/AssemblyAttributes.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlDistributedLockFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlInstallerFacts.cs, tests/Hangfire.PostgreSql.Tests/Utils/ConnectionUtils.cs
Potentially fixes #119.
Potentially fixes #237.
Fixes #271.
Fixes #274.
Changes how the transaction scope is opened - respects already-present ambient transaction.
Defaults `EnableTransactionScopeEnlistment` to `true` as that is the default behaviour in most of the ADO.NET providers anyway.
=> Fixed the transaction-related issues

src/Hangfire.PostgreSql/PostgreSqlJobQueueMonitoringApi.cs
Before it was not being order which made it difficult to monitor.
=> In the hangfire dashboard, order the jobs by date.

src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, src/Hangfire.PostgreSql/Utils/DbConnectionExtensions.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlJobQueueFacts.cs
Test is failing for Postgres 9.6. This request includes the following:
- Long-polling (Notifications) test has been fixed to test scenarios where the database is lower than Postgres 11.
- Missing database version check was added job enqueue function.
=> Long polling test fix

README.md, src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs
From the very first commit, the `PostgreSqlJobQueue` had `fetchConditions` array containing two conditions:
1. Selecting jobs where `fetchedat` = NULL,
2. Selecting old jobs where `fetchedat` is earlier than `InvisibilityTimeout`.
In job-fetching loop this conditions array generated two consecutive SQL queries with no delay between them if the queue is empty. 
So, I combined these two conditions into one query and aligned the results with order clause.
```
WHERE ...
(""fetchedat"" IS NULL OR ""fetchedat"" < NOW() + INTERVAL '{timeoutSeconds.ToString(CultureInfo.InvariantCulture)} SECONDS')
ORDER BY ""fetchedat"" NULLS FIRST, ...
```
Half the number of SQL queries are needed for fetching 😆.
=> Combine two consecutive SQL queries for fetching jobs into one

src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs, src/Hangfire.PostgreSql/Utils/AutoResetEventRegistry.cs
There was a significant issue with the new enqueued job trigger that should release waiting in jobs fetching loops. It used only one static `AutoResetEvent` instance for all workers and queues. When this `AutoResetEvent` is released, it only releases one random waiting thread. If it was a thread of a worker with a different queue, the job gets stuck until a new event or the `QueuePollInterval` passes. This situation frequently occurred in my environment.
- Introduced new class `AutoResetEventRegistry` in place of one `AutoResetEvent`. It internally holds several `AutoResetEvent` instances, one for each queue.
- Moved its triggering from `PostgreSqlStorage `to `PostgreSqlWriteOnlyTransaction`, where new jobs are added and committed. The list `_queuesWithAddedJobs` accumulates all queues …
=> Fixing Enqueued Job Trigger for Multiple Queues

src/Hangfire.PostgreSql/Factories/NpgsqlConnectionFactory.cs, src/Hangfire.PostgreSql/Factories/NpgsqlInstanceConnectionFactoryBase.cs, src/Hangfire.PostgreSql/PostgreSqlBootstrapperOptions.cs
Fixes issue #343 
Refactor NpgsqlInstanceConnectionFactoryBase to return updated connection string builder instances when connection string changes.
=> Return new connection string builder instance if connection string changes

.github/workflows/ci.yml, .github/workflows/pack.yml
Update ci workflow actions to latest versions since older versions are running on node version 16 which is deprecated and will stop being available in Github from mid May.
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> Update CI/Pack workflow actions to latest version to ensure they can run on Node 20

src/Hangfire.PostgreSql/PostgreSqlConnection.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlConnectionFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageFacts.cs
See issue #368 for discussion.
Hangfire.Core 1.8.12 introduces parallelism support for `DelayedJobScheduler` and `RecurringJobScheduler`. That support requires the storage layer to allow batched retrieval of scheduled/recurring jobs, which is done by overriding the List-returning `GetFirstByLowestScoreFromSet`.
Hangire.Core's sheduler parallelism is implemented fully within the `DelayedJobScheduler` and `RecurringJobScheduler` methods:
1. acquires a distributed `scheduler` or `recurring-jobs` lock, respectively
2. calls `GetFirstByLowestScoreFromSet` to retrieve the `List` of IDs for the to-be-enqueued jobs
3. performs a Parallel.ForEach over the `List` of IDs
i. uses the `MaxDegreeOfParallelism` configured when Hangfire is started
ii. enqueues each job, during which it acquires a …
=> #368 allow scheduler parallelism

src/Hangfire.PostgreSql/PostgreSqlFetchedJob.cs, src/Hangfire.PostgreSql/PostgreSqlHeartbeatProcess.cs, src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs, src/Hangfire.PostgreSql/PostgreSqlStorage.cs, src/Hangfire.PostgreSql/PostgreSqlStorageOptions.cs, src/Hangfire.PostgreSql/Utils/ExceptionTypeHelper.cs, src/Hangfire.PostgreSql/Utils/TimestampHelper.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlFetchedJobFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlJobQueueFacts.cs
This adds the sliding invisibility timeouts functionality (from [#209](https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/209)) which is ported from SQL Server storage.
(_This also ports a change where when removing from queue or requeuing, it will include the fetchedat in the where clause. See this [commit](https://github.com/HangfireIO/Hangfire/commit/c6f067ef588daf4a22a8306f72e6f0d70b54955f#diff-d1c9a00ca08dbbfa1e03e27d0ff0e7861ccfbd5931e6f8853074f3608dd52095) (Check FetchedAt has expected value to prevent prolonging other's work)._)
As noted in the original ticket, sliding invisibility timeouts is better than invisibility timeouts since as long as the worker instance is running, it will never reassign the job to another worker.  This is much better than setting the …
=> #209 - Add Support for Sliding Invisibility Timeouts

src/Hangfire.PostgreSql/CountersAggregator.cs, src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs, tests/Hangfire.PostgreSql.Tests/CountersAggregatorFacts.cs, tests/Hangfire.PostgreSql.Tests/PostgreSqlMonitoringApiFacts.cs, tests/Hangfire.PostgreSql.Tests/Scripts/Clean.sql
Fixes #333.
Apparently we've missed adding the union from aggregatedcounter table for hourly stats.
=> Read aggregated counter table too for hourly stats

src/Hangfire.PostgreSql/Scripts/Install.v23.sql, tests/Hangfire.PostgreSql.Tests/Hangfire.PostgreSql.Tests.csproj
Runtime : .Net9.0
Postgres Version : postgres:10 alpine
Error:
In PostgreSQL 10, Hangfire.PostgreSql encountered an error during index creation: "syntax error at or near 'INCLUDE'." This happened because the INCLUDE clause is not supported in this version, causing the migration to fail.
Solution: To resolve this, the script now dynamically checks for INCLUDE compatibility. If supported, the index is created with INCLUDE; otherwise, a fallback version without INCLUDE is used. This ensures compatibility with PostgreSQL and later versions.
=> Validate INCLUDE compatibility for index creation in PostgreSQL #390

src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs, src/Hangfire.PostgreSql/PostgreSqlDistributedLockException.cs
Closes #386 
Changed distributed lock exception type so it doesn't bubble up as error level event
=> Changed distributed lock exception type

src/Hangfire.PostgreSql/Scripts/Install.v23.sql
Fix for: https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/404
=> Use EXECUTE for index creation for compatibility with older PostgreSQL versions.
