hangfire-postgres/Hangfire.PostgreSql

src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj
src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs
src/Hangfire.PostgreSql/Utils/TryExecute.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlJobQueueFacts.cs

Also fixed the unit test failing due to the orders of dequeued jobs

Dequeue jobs within a repeatable-read transaction

---

src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs

Fixed the smoother function for multiple dequeues

---

src/Hangfire.PostgreSql/PostgreSqlStorage.cs

I plan to run multiple applications off of a single Postgres database with a different schema per application. It would be handy to see this information show up on the Dashboard.

Adding schema to Storage ToString

---

src/Hangfire.PostgreSql/PostgreSqlConnection.cs

This change enables "Retries" section on Hangfire Dashboard

Extend JobStorageConnection on PostgreSqlConnection

---

src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj
src/Hangfire.PostgreSql/Install.v6.sql

Add indices, greatly speeds-up deleting old jobs

---

src/Hangfire.PostgreSql.NetCore/project.json

Wrong configuration value causes this error - https://ci.appveyor.com/project/vytautask/hangfire-postgresql-lel5h/build/1.4.0.22#L401

Fix postcompile build step

---

src/Hangfire.PostgreSql/ExpirationManager.cs
src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj
src/Hangfire.PostgreSql/Install.v8.sql
src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs
src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs
tests/Hangfire.PostgreSql.Tests/ExpirationManagerFacts.cs

Hello guys,
I've fixed infinite growth of counters table. During expiration maintenance it folds all records into one record for each state. This should greatly increase the performance and reduce usage of storage.

Implemented aggregation for counter table

---

src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlMonitoringApiFacts.cs

Fixes issues such as https://github.com/frankhommers/Hangfire.PostgreSql/issues/79

Fix KeyNotFoundException

---

src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj

https://github.com/frankhommers/Hangfire.PostgreSql/issues/83

issues-83, downgrade the version of Newtonsoft.Json to 10.0.1

---

src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlDistributedLockFacts.cs

Add missing `resource` SQL clause

Fix lock acquisition logic for Init_UpdateCount

---

src/Hangfire.PostgreSql/Install.v10.sql
src/Hangfire.PostgreSql/Install.v8.sql
src/Hangfire.PostgreSql/Install.v9.sql

Fix installation version check

---

src/Hangfire.PostgreSql/Scripts/Install.v12.sql

New Install.v12.sql file altering all VARCHAR(n) fields to TEXT in all tables. Resolving #113 .

Altering all VARCHAR(n) fields to TEXT

---

README.md

A bit of reformatting + added SSL suppport example

Added SSL support docs

---

src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs

Pull request #137 introduced a regression as it added a significant delay in job processing latency.
Previously NewItemInQueueEvent was raised within the current pending transaction. Therefore the queue could not retrieve the added job, as it was not visible to the queue yet.
Changed the logic so that NewItemInQueueEvent gets raised **after** the transaction scope is completed.
_TransactionCompleted_ event is required here, because if this TransactionScope is enlisted within an ambient TransactionScope, the ambient TransactionScope controls when the TransactionScope completes.
**Currently:**
**With this MR:**

Raise NewItemInQueueEvent after transaction scope has completed - Reduce job latency

---

src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs

Silently swallowing the exception when trying to lock resources is not always a good idea. This PR does add the logging for when the resource actually fails to get locked. Could make it configurable if necessary.
The actual problem which has been hidden by swallowing is that the stale connection can be used when locking the resources. If the connection gets closed (not by the code, but infrastructure/server issues) while executing any of the scripts, all the retries are happening with a closed connection, which of course would never work without explicitly opening it.

Fixed distributed lock connection state

---

src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlJobQueueFacts.cs

This allows a Job server implementation to Interrupt the PollQueue waiting thread and trigger a new Poll for immediate job processing when implemented via an external trigger.

[Feature] Added method for fetching a new job in the job queue

---

src/Hangfire.PostgreSql/PostgreSqlJobQueueMonitoringApi.cs

Removed space between Schema and Table in SQL template 
#219

Relation "hangfire .jobqueue" does not exist

---

src/Hangfire.PostgreSql/Scripts/Install.v16.sql
tests/Hangfire.PostgreSql.Tests/PostgreSqlInstallerFacts.cs

This PR addresses #192 by changing the remaining `integer` sequences to be `bigint`

Change remaining sequences from integer to bigint to match job_id_seq

---

.editorconfig
src/Hangfire.PostgreSql/EnvironmentHelpers.cs
src/Hangfire.PostgreSql/ExpirationManager.cs
src/Hangfire.PostgreSql/PersistentJobQueueProviderCollection.cs
src/Hangfire.PostgreSql/PostgreSqlBootstrapperConfigurationExtensions.cs
src/Hangfire.PostgreSql/PostgreSqlConnection.cs
src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs
src/Hangfire.PostgreSql/PostgreSqlFetchedJob.cs
src/Hangfire.PostgreSql/PostgreSqlJobQueue.cs
src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs
src/Hangfire.PostgreSql/PostgreSqlObjectsInstaller.cs
src/Hangfire.PostgreSql/PostgreSqlStorage.cs
src/Hangfire.PostgreSql/PostgreSqlStorageOptions.cs
src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs
src/Hangfire.PostgreSql/Utils/TryExecute.cs
tests/Hangfire.PostgreSql.Tests/GlobalSuppressions.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlConnectionFacts.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageOptionsFacts.cs

- Introduced minimum value for queue poll interval, which is possible to override if the devs actually want it (only exception - `TimeSpan.Zero`).
- Fixed code style to conform with new .editorconfig file.
Solves #229, except I did not add any xmldocs. Maybe another time.

Introduce minimum value for queue poll interval

---

src/Hangfire.PostgreSql/PostgreSqlBootstrapperConfigurationExtensions.cs
src/Hangfire.PostgreSql/PostgreSqlStorage.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageFacts.cs

Fixed argument name and error message regarding connection strings

---

src/Hangfire.PostgreSql/PostgreSqlStorage.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlWriteOnlyTransactionFacts.cs

Fixed TransactionAbortedException due to a prepared transaction when enqueuing a job within a transaction when TransactionScopeEnlistment is enabled

---

src/Hangfire.PostgreSql/IConnectionFactory.cs
src/Hangfire.PostgreSql/PostgreSqlStorage.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageFacts.cs
tests/Hangfire.PostgreSql.Tests/Utils/DefaultConnectionFactory.cs

Builds upon work by #251 with further changes as per discussion at https://github.com/frankhommers/Hangfire.PostgreSql/issues/251#issuecomment-1149337624

Fix transient Collection was Modified exception (Issue #251)

---

src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs

my first git pr, test ok  fix #261

add ExpireAt in JobDetailsDto

---

src/Hangfire.PostgreSql/Scripts/Install.v19.sql
tests/Hangfire.PostgreSql.Tests/PostgreSqlInstallerFacts.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlMonitoringApiFacts.cs

Change type of timestamp columns

---

src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs

This will fixes GetStatistics sql command error.

GetStatistics sql command fix

---

src/Hangfire.PostgreSql/PostgreSqlStorage.cs

This is a fix for https://github.com/frankhommers/Hangfire.PostgreSql/issues/163

Fix for connection leak related to transactions.

---

src/Hangfire.PostgreSql/PostgreSqlDistributedLock.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlDistributedLockFacts.cs

When not using transactions we do not clear the expired locks, meaning the specific resources might be locked forever unless someone clears them out manually.
Fixes #273.

Remove expired lock when using updatecount

---

src/Hangfire.PostgreSql/JsonParameter.cs
src/Hangfire.PostgreSql/PostgreSqlConnection.cs
src/Hangfire.PostgreSql/PostgreSqlObjectsInstaller.cs
src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs
src/Hangfire.PostgreSql/Scripts/Install.v20.sql
tests/Hangfire.PostgreSql.Tests/ExpirationManagerFacts.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlConnectionFacts.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlInstallerFacts.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlJobQueueFacts.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlMonitoringApiFacts.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlStorageFacts.cs
tests/Hangfire.PostgreSql.Tests/PostgreSqlWriteOnlyTransactionFacts.cs
tests/Hangfire.PostgreSql.Tests/Utils/PostgreSqlTestObjectsInitializer.cs

Change columns to jsonb where possible

---

src/Hangfire.PostgreSql/Hangfire.PostgreSql.csproj
src/Hangfire.PostgreSql/PostgreSqlStorage.cs
tests/Hangfire.PostgreSql.Tests/Entities/TestJob.cs
tests/Hangfire.PostgreSql.Tests/FirstClassQueueFeatureSupportTests.cs

Implementation for https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/303
**Things to consider**
- Fix is really just enabling the feature inside `HasFeature` method, no extra changes expected
- Upgrading Hangfire.Core package is required in order to override `public override bool HasFeature` method (it was added recently)
- But upgrading Core will force all postgres consumer to upgrade too which might not be good
- Please advice how to proceed here. I can see an option like releasing an rc ourselves, but it need to be discussed anyway
- This is in `Draft` until I have some time to at least run a full Hangfire instance properly. I only ran a single test, which seems good, but I'm not confident this didn't break anywhere else. 
New `Queue` property serializes just fine. See …

First class queue support

---

src/Hangfire.PostgreSql/PostgreSqlWriteOnlyTransaction.cs

Fix new jobs signalling in case of ambient transaction #331

---

src/Hangfire.PostgreSql/PostgreSqlObjectsInstaller.cs

Fix schema version update in PostgreSqlObjectsInstaller on script failure

---

src/Hangfire.PostgreSql/ExpirationManager.cs

- Update Expiration manager to commit the database transaction once per batch. 
Fixes https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/347

feat: expiration manager commiting deletes in batches

---

src/Hangfire.PostgreSql/Scripts/Install.v22.sql
tests/Hangfire.PostgreSql.Tests/PostgreSqlInstallerFacts.cs

Attempt to fix #348
Create index for jobqueue table that puts NULLs in "fetchedat" column first for better de-queueing performance

[#348] Improve dequeue performance

---

src/Hangfire.PostgreSql/Scripts/Install.v23.sql
tests/Hangfire.PostgreSql.Tests/PostgreSqlInstallerFacts.cs

linked to https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/367

#367 - Improve job count by state query performance
